### ISSUE TITLE
Example of Amplify environment variables with SvelteKit

### ISSUE THREAD

**Issue by msambol** [gzimbron/amplify-adapter#10]
Hi, Gustavo! Thank you for this. This isn't an issue with your repo but I'm wondering if you have any examples of properly setting environment variables. I have the following:

`.env`:
```
REGION=us-east-2
ACCESS_KEY_ID=yyy
SECRET_ACCESS_KEY=xxx
```

Then in `src/lib/server/ddb.ts` I have:
```ts
import { env } from '$env/dynamic/private';

const client = new DynamoDBClient({
  region: env.REGION || '',
  credentials: {
    accessKeyId: env.ACCESS_KEY_ID || '',
    secretAccessKey: env.SECRET_ACCESS_KEY || '',
  }
});
```

This works when running locally. I read [here](https://docs.aws.amazon.com/amplify/latest/userguide/ssr-environment-variables.html) that there is extra work for making environment variables available for server-side runtimes so I tried the following:

```
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - npm ci
        build:
          commands:
            - echo "REGION=$REGION" >> .env
            - echo "ACCESS_KEY_ID=$ACCESS_KEY_ID" >> .env
            - echo "SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY" >> .env
            - npm run build
            - cd build/compute/default/
            - npm i --production
      artifacts:
        baseDirectory: build
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
          - .npm/**/*
    appRoot: svelte
```

This doesn't seem to work. Have you had success with environment variables?
