### ISSUE TITLE
Missing required-server-files.json

### ISSUE THREAD

**Issue by christowiz** [gzimbron/amplify-adapter#8]
The build process completes but fails at the end

![image](https://github.com/gzimbron/amplify-adapter/assets/597282/1e18c743-9bf0-48c1-b9a2-0373488f9ec0)

**Comment by gzimbron** [comment]
Hello @christowiz , could you please share your amplify adapter version, and amplify yml ?

**Comment by christowiz** [comment]
Sure, @gzimbron.

I'm using version `0.1.2`

```yaml
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - npm i -g pnpm@8.8.0
            - echo "//npm.pkg.github.com/:_authToken=${GITHUB_NPM_TOKEN}" >> ~/.npmrc
            - echo "node-linker=hoisted" >> ~/.npmrc
            - pnpm install --prefer-frozen-lockfile
        build:
          commands:
            - pnpm exec nx run apps/jupiter-poc:build
            - cd apps/jupiter-poc/build/compute/default/
            - npm i --production
      artifacts:
        baseDirectory: apps/test-app/build
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
      buildPath: /
    appRoot: apps/test-app

```
